// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA73lW47sgpxvCkjsbkoVADTznyX-TQh3M',
    appId: '1:240439362542:web:4692f3c14e01e1f76884ff',
    messagingSenderId: '240439362542',
    projectId: 'scheduler-pro-3d24d',
    authDomain: 'scheduler-pro-3d24d.firebaseapp.com',
    storageBucket: 'scheduler-pro-3d24d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6hxMGMRu6vDpqead7aWLhScTgKA1GSo4',
    appId: '1:240439362542:android:1a5568152d55f4096884ff',
    messagingSenderId: '240439362542',
    projectId: 'scheduler-pro-3d24d',
    storageBucket: 'scheduler-pro-3d24d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3KZuiWGs7NcxFOsRxowB0fL7xa_9C1YU',
    appId: '1:240439362542:ios:aa7cb7550979e7186884ff',
    messagingSenderId: '240439362542',
    projectId: 'scheduler-pro-3d24d',
    storageBucket: 'scheduler-pro-3d24d.appspot.com',
    iosBundleId: 'com.example.schedulerPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3KZuiWGs7NcxFOsRxowB0fL7xa_9C1YU',
    appId: '1:240439362542:ios:ecd968e51acb926b6884ff',
    messagingSenderId: '240439362542',
    projectId: 'scheduler-pro-3d24d',
    storageBucket: 'scheduler-pro-3d24d.appspot.com',
    iosBundleId: 'com.example.schedulerPro.RunnerTests',
  );
}
